# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias rm='rm -i'
alias fix-monitors='xrandr --output LVDS1 --off && xrandr --output HDMI1 --auto'

#just some handy stuff
alias zshrc='vim ~/.zshrc'
alias bashrc='vim ~/.bashrc'
